
const translations = {
    "Sample Book": {
        english: "One bright morning, Aling Nena woke up early to go to the market. She brought her son, Nilo, with her so he could learn how to buy fresh and healthy food. The market was lively—people were busy walking around, vendors were calling out their products, and buyers were bargaining for lower prices. As soon as they entered, they saw rows of fresh vegetables. There were green pechay, cabbage, eggplants, tomatoes, and squash. Aling Nena taught Nilo how to choose fresh vegetables—leaves should not be wilted, the color should be bright, and there should be no bruises. They carefully selected what they needed and placed them in their basket. Next, they went to the fish section. Nilo noticed the smell of the sea from the freshly caught fish. His mother explained that fresh fish have clear eyes and red gills. They bought milkfish and a few pieces of tilapia for dinner. They also stopped by the meat section. Nilo observed how the butcher weighed and sliced the pork and chicken. His mother reminded him that cleanliness is important when buying meat. Of course, they did not forget to visit the fruit stalls. They bought sweet mangoes, bananas, and watermelon. Nilo was amazed by the many colors and varieties of fruits. As they walked around, Nilo noticed the different people in the market—the hardworking vendors, the buyers negotiating prices, and children helping their parents. He realized that the market is not only a place to buy and sell but also a place where people work together to earn a living. Before going home, they bought some warm rice cakes for snacks. When they arrived home, Nilo happily shared what he had learned. He helped his mother wash the vegetables and prepare the meal. That day, Nilo learned the value of being wise with money, being observant, and helping his parents. He also understood the importance of appreciating the hardworking people in the market.",
        tagalog: "Isang maaliwalas na umaga, maagang nagising si Aling Nena upang mamalengke. Isinama niya ang kanyang anak na si Nilo upang matuto ito kung paano mamili ng sariwa at masustansyang pagkain. Masigla ang paligid ng palengke—maraming tao, makukulay ang mga paninda, at maririnig ang tawaran ng mga mamimili at tindera. Pagpasok pa lamang nila, bumungad agad ang hanay ng mga gulay. May mga luntiang pechay, repolyo, talong, kamatis, at kalabasa. Ipinaliwanag ni Aling Nena kay Nilo kung paano pumili ng sariwang gulay—dapat makintab ang balat, hindi lanta ang dahon, at walang sira o pasa. Maingat silang namili at inilagay sa bayong ang kanilang mga napili. Sumunod naman silang pumunta sa tindahan ng isda. Naamoy ni Nilo ang sariwang simoy ng dagat mula sa mga bagong huling isda. Itinuro ng kanyang ina na ang sariwang isda ay may malinaw na mata at mapulang hasang. Bumili sila ng bangus at ilang pirasong tilapia para sa kanilang hapunan. Dumaan din sila sa bilihan ng karne. Pinagmasdan ni Nilo kung paano tumitimbang ang magtataho at kung paano hinihiwa ng magkakarne ang baboy at manok. Tinuruan siya ng kanyang ina na dapat tiyaking malinis ang pwesto at maayos ang pagkakatago ng karne. Hindi mawawala ang bahagi ng palengke na puno ng prutas. Namili sila ng matatamis na mangga, saging, at pakwan. Tuwang-tuwa si Nilo sa dami ng kulay at uri ng prutas na kanyang nakita. Habang naglalakad, napansin ni Nilo ang iba't ibang tao sa palengke—mga tindera na masipag na nag-aalok ng paninda, mga mamimiling tumatawad, at mga batang katulad niya na inuutusan ng kanilang mga magulang. Napagtanto niya na ang palengke ay hindi lamang lugar ng bentahan kundi lugar din ng ugnayan at pagtutulungan. Bago umuwi, bumili sila ng mainit na puto at suman bilang meryenda. Pagdating sa bahay, masayang ikinuwento ni Nilo ang kanyang mga natutuhan. Tinulungan niya ang kanyang ina sa paghuhugas ng mga gulay at paghahanda ng pagkain. Sa araw na iyon, natutunan ni Nilo ang kahalagahan ng pagiging matipid, mapanuri, at masipag. Napagtanto rin niya ang halaga ng bawat taong nagtatrabaho sa palengke upang magkaroon ng pagkain ang bawat pamilya."
    },
    "Batang Maraming Bawal": {
        english: "There was a young boy who always heard the word Don't from his parents. Don't run inside the house. Don't play on the street. Don't stay up late. Don't eat sweets before dinner. Almost everything he did came with a warning. Because of this, the boy felt that there were too many things he was not allowed to do. He was envious of other children who seemed free to play and have fun. He wondered why he had so many don'ts. One day, he decided to test some of the rules. He ran inside the house and almost tripped. He also went out to play on the street without permission and nearly got hit by a bicycle. That's when he slowly began to understand why his parents had set these rules. His mother explained that the don'ts were not meant to restrict him but to protect him. The rules were guidelines to keep him safe and healthy. In the end, the boy realized that the rules were a sign of his parents' love and care. He learned to follow them and understood the importance of discipline.",
        tagalog: "May isang batang lalaki na laging nakakarinig ng salitang Bawal mula sa kanyang mga magulang. Bawal tumakbo sa loob ng bahay. Bawal maglaro sa kalsada. Bawal magpuyat. Bawal kumain ng matatamis bago maghapunan. Halos lahat ng kanyang gawin ay may kasunod na paalala. Dahil dito, pakiramdam ng bata ay napakarami niyang hindi maaaring gawin. Naiinggit siya sa ibang mga bata na tila malayang nakakapaglaro at nakakapaglibang. Iniisip niya kung bakit siya lamang ang may napakaraming bawal. Isang araw, sinubukan niyang suwayin ang ilan sa mga ipinagbabawal. Tumakbo siya sa loob ng bahay at muntik nang madapa. Lumabas din siya upang maglaro sa kalsada nang walang paalam at muntik nang masagi ng bisikleta. Doon niya unti-unting naunawaan kung bakit may mga alituntunin ang kanyang mga magulang. Ipinaliwanag sa kanya ng kanyang ina na ang mga bawal ay hindi para siya paghigpitan, kundi para siya protektahan. Ang mga patakaran ay gabay upang siya'y manatiling ligtas at malusog. Sa huli, napagtanto ng bata na ang mga ipinagbabawal ay pagpapakita ng pagmamahal at pag-aalaga ng kanyang mga magulang. Natuto siyang sumunod at umunawa sa kahalagahan ng disiplina."
    },
    "Pagong at Matsing": {
        english: "One day, a tortoise and a monkey were walking by the river. They saw a banana tree full of fruit. Both wanted to share the bananas, but they couldn't agree on how. The monkey suggested that he pick first. The tortoise agreed, but the monkey planned to trick him. The monkey took the biggest and sweetest bananas for himself and left the smaller, less ripe ones for the tortoise. The tortoise did not get angry. Instead, he used his wisdom and patience. He waited for the right moment. When the monkey wandered off and forgot some bananas, the tortoise carefully gathered the fallen and unnoticed bananas. In the end, the tortoise ended up with more bananas than the monkey.",
        tagalog: "Isang araw, may pagong at matsing na naglakad sa tabi ng ilog. Nakakita sila ng isang punong saging na may maraming bunga. Nais nilang hatiin ang saging, pero hindi sila nagkasundo kung paano. Iminungkahi ng matsing na siya ang mauuna sa pagpili ng saging. Ang pagong ay pumayag, ngunit may plano ang matsing na lokohin siya. Kinuha ng matsing ang pinakamatamis at pinakamalaking saging para sa sarili, at iniwan ang maliit at hindi gaanong hinog sa pagong. Hindi nagalit ang pagong. Sa halip, ginamit niya ang talino at tiyaga. Hinintay niya ang pagkakataon. Nang makalayo ang matsing at makalimutan ang saging, dahan-dahan niyang kinuha ang mga saging na nahulog at mga hindi napansin ng matsing. Sa huli, nakakuha rin ang pagong ng mas marami sa huli kaysa sa matsing."
    },
    "Sari Sari Summers": {
        english: "Nora is a young girl who loves spending her summers with her lola (grandmother) at her grandmother's sari-sari store — a small neighborhood shop that sells all sorts of things like snacks, toys, hair accessories, and candies. This year, Nora is finally old enough to help her lola run the store. At first, she eagerly helps by restocking items, cleaning, and measuring goods for customers. But when a heat wave hits, the streets grow quiet and no one comes to the store. Nora begins to worry that she won't get to spend the rest of the summer with her lola helping out. While resting under a mango tree outside the store, Nora notices the ripe mangoes hanging on the branches. She gets a bright idea — together with her lola, they start making refreshing mango ice candy (a sweet cold treat) by measuring, mixing, and tasting the ingredients. They sell the ice candy at the store, and soon neighbors start coming again, not just for the treats but also for everyday items from the sari-sari store. Throughout the summer, Nora and her lola make different flavors of ice candy, bringing joy and community back to the store. The story celebrates creativity, family bonds, and Filipino summer life — and even includes a simple recipe for the mango ice candy.",
        tagalog: "Si Nora ay isang batang babae na tuwing tag-init ay nananatili sa kanyang lola para tumulong sa maliit na sari-sari store — isang tindahan sa kanto na nagbebenta ng iba't ibang bagay tulad ng mga kendi, paminta, laruan, at mga pang-araw-araw na kailangan. Ngayong taon, sapat na ang edad ni Nora para makatulong sa kanyang lola. Masaya siyang naglilinis, nagsasaayos ng mga paninda, at tumutulong magbenta ng mga produkto sa mga parokyano. Ngunit isang araw, dumating ang isang matinding init ng panahon — walang gaanong pumapasok na mga mamimili dahil sobrang init. Dahil dito, nag-aalala si Nora na baka hindi na maging masaya ang natitirang bahagi ng kanyang tag-init kasama ang kanyang lola. Habang sila ay nagpapahinga sa lilim ng isang manggatang puno sa labas ng tindahan, napansin ni Nora na may mga hinog na mangga doon. Nagkaroon siya ng ideya: bakit hindi sila gumawa ng ice candy (pinapalamig na panghimagas) gamit ang mangga? Magkasama nilang hinanda ang mango ice candy — sinukat, hinalo, at tinikman hanggang sa maging masarap ang timpla. Ibinenta nila ito sa sari-sari store, at unti-unti bumalik ang mga tao sa tindahan para bumili hindi lang ng ice candy kundi pati na rin ng iba pang mga paninda. Sa natitirang bahagi ng tag-init, si Nora at ang kanyang lola ay gumawa at nagbenta ng iba't ibang lasa ng ice candy, na nagdala ng saya at komunidad sa maliit nilang tindahan."
    }
};

let currentLanguage = 'english';

function getTranslation(title, language) {
    const story = translations[title];
    if (story) {
        return story[language] || story['english'];
    }
    return '';
}

function toggleLanguage() {
    currentLanguage = currentLanguage === 'english' ? 'tagalog' : 'english';
    updateStoryLanguage();
}

function updateStoryLanguage() {
    const titleElement = document.getElementById('bookTitle');
    const storyElement = document.getElementById('bookStory');
    const toggleBtn = document.getElementById('langToggle');
    
    if (titleElement && storyElement) {
        const title = titleElement.textContent;
        const story = getTranslation(title, currentLanguage);
        storyElement.textContent = story;
    }
    
    if (toggleBtn) {
        toggleBtn.textContent = currentLanguage === 'english' ? 'Switch to Tagalog' : 'Switch to English';
    }
}
